### ISSUE TITLE
Pull base image before build

### ISSUE THREAD

**Issue by leafty** [SwissDataScienceCenter/renku-project-template#1]
Insert here: https://github.com/SwissDataScienceCenter/renku-project-template/blob/b24fe41145091f704c8e81612ef9121a98fedc7f/latest/.gitlab-ci.yml#L18

**Comment by rokroskar** [comment]
why? which base image?

**Comment by leafty** [comment]
insert `docker pull renku/singleuser:latest`
Issue is that you want to pull patches to the base image, like for git LFS.
