### ISSUE TITLE
kernel names cannot have spaces

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-project-template#10]
If a project has spaces in the name, the kernel creation fails -- need to escape spaces (or perhaps also other characters?)

**Comment by leafty** [comment]
@rokroskar see https://github.com/SwissDataScienceCenter/renku-ui/issues/319

**Comment by rokroskar** [comment]
ok good -- this should be either done asap or the current "latest" template deferred until it is resolved.

**Comment by rokroskar** [comment]
I think this is a non-issue since we no longer make conda environments with the project name
