### ISSUE TITLE
Update Julia template to latest image

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-project-template#102]
# Description

https://github.com/SwissDataScienceCenter/renkulab-docker/pull/115 introduces a new image based on the current stable version of Julia (1.5.3). The Julia template should be updated to be in sync.

**Comment by gavin-k-lee** [comment]
I'd like to follow up on this since I'm adding a Julia tutorial.

The most current stable version is 1.6.1 and the Dockerfile in this repo is quite old - it doesn't have this bit
```
# RENKU_VERSION determines the version of the renku CLI
# that will be used in this image. To find the latest version,
# visit https://pypi.org/project/renku/#history.
ARG RENKU_VERSION=0.14.2

########################################################
# Do not edit this section and do not add anything below

RUN if [ -n "$RENKU_VERSION" ] ; then \
    pipx uninstall renku && \
    pipx install --force renku==${RENKU_VERSION} \
    ; fi

########################################################
```
and uses `renku --version == 0.10.4` so `renku dataset`'s `name` tag doesn't work.
