### ISSUE TITLE
chore: update docker files to v0.7.6

### ISSUE THREAD

**Issue by gavin-k-lee** [SwissDataScienceCenter/renku-project-template#115]
The latest project templates should be updated to 0.7.6, e.g.
https://github.com/SwissDataScienceCenter/renku-project-template/blob/bc0fee721f63359e6a27982cd5dd7df5cec81be4/R-minimal/Dockerfile#L3

Several R mirrors are out of date with 0.7.5, see https://github.com/SwissDataScienceCenter/renkulab-docker/issues/163

**Comment by gavin-k-lee** [comment]
The manifest also needs to be updated:

https://github.com/SwissDataScienceCenter/renku-project-template/blob/bc0fee721f63359e6a27982cd5dd7df5cec81be4/manifest.yaml#L17

**Comment by lorenzwalthert** [comment]
Cool, thanks. Maybe there's a way to check these tags are up-to-date with a GitHub Action or similar with a simple `/bin/bash grep` to make sure newly released docker images are included in all downstream dependencies.
