### ISSUE TITLE
pre-populate source code part of the project

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-project-template#12]
A suggestion was made to create a `src/python` directory with the necessary things inside to make `pip install src/python/<project-name>` work.

This is needed in order to make it easy for users to refactor early.

**Comment by pameladelgado** [comment]
I think this issue is not necessary/valid any more, right @rokroskar ?

**Comment by rokroskar** [comment]
Hmm not sure - we've not really gone in that direction and no one has been asking for it. I think it's safe to close for now.
