### ISSUE TITLE
Consider using branches/tags instead of folders

### ISSUE THREAD

**Issue by jirikuncar** [SwissDataScienceCenter/renku-project-template#15]
The number of subdirectories for each released version might be huge. It is also a bit more difficult to apply and propagate patches from older templates.

**Comment by rokroskar** [comment]
I'm fine with this, but it requires changes in the UI.

**Comment by ableuler** [comment]
Hmm, removing the folders would break some existing deployments, so at least the `0.2.0` folder has to stick around.

**Comment by jirikuncar** [comment]
we can keep `maint-0.2.0` as default branch while working on master which will have a new structure

**Comment by jirikuncar** [comment]
@ableuler does Renku-UI require GitHub to be up?

**Comment by ableuler** [comment]
For project creation, currently yes

**Comment by ciyer** [comment]
We have adopted this way of doing the templates with #28 .
