### ISSUE TITLE
Add server options to the project's config file

### ISSUE THREAD

**Issue by vfried** [SwissDataScienceCenter/renku-project-template#29]
# Description
We should allow the user to specify default server_options, e.g. `default_url`. These runtime parameters should go in a `config.ini` file in the project root directory. 

Examples of this include:
* Environment resource requirements (e.g., an interactive environment for this project requires 2 GPUs and 16G of memory)
* The URL to connect to (e.g., jupyterlab or rstudio)

**Comment by rokroskar** [comment]
I would argue the `config.ini` should be in the `.renku` directory rather than in the root of the project (like e.g. `.git/config`). We should outline in this issue what the structure of the configuration file should look like.

**Comment by rokroskar** [comment]
https://github.com/SwissDataScienceCenter/renku-python/issues/730 implements local project configuration so this can be implemented as soon as that PR is merged.

**Comment by rokroskar** [comment]
We should discuss what this configuration should look like, i.e. what sections we need to create. Could be as simple as

```
[interactive]
    default_url = /lab
    cpu_request = 2
```
