### ISSUE TITLE
Store a link to the source template

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-project-template#34]
# Description

When a template is instantiated, the metadata should include a link to the exact template (including version) from which it came.

**Comment by rokroskar** [comment]
Is this really a template issue? Seems like it should be a UI/CLI issue. If you agree, please transfer.

**Comment by ciyer** [comment]
The thinking was that the template would a metadata file with a template variable for its URL that would be filled in as part of the template instantiation process (just as project name is). This would ensure consistency of the way the information was stored.

We could, as you suggest, push this responsibility to the UI/CLI as part of the template instantiation process, we would just need to coordinate to ensure the information is stored in the same place/way.

**Comment by rokroskar** [comment]
I see so that would be an additional template variable. I guess it should be in (at least) two places then.

**Comment by rokroskar** [comment]
Could we add this as a [`prov:wasDerivedFrom`](https://www.w3.org/TR/prov-o/#wasDerivedFrom) property? The metadata would then look something like

```
created: '2019-11-04T09:36:39.254776+00:00'
creator: mailto:rok.roskar@sdsc.ethz.ch
name: test-init
updated: '2019-11-04T09:36:39.257894+00:00'
derivedFrom: https://github.com/SwissDataScienceCenter/renku-project-template@v0.1.2
```

**Comment by rokroskar** [comment]
https://github.com/SwissDataScienceCenter/renku-python/pull/1469 enables this functionality and it should be implemented.

**Comment by rokroskar** [comment]
All metadata in `.renku` is handled by renku-python now and this functionality has been implemented.
