### ISSUE TITLE
Add install.R to parallel requirements.txt but for R projects

### ISSUE THREAD

**Issue by emmjab** [SwissDataScienceCenter/renku-project-template#51]
There's no widely accepted way to include dependencies in R projects, but one way is to include an install.R file (@cchoirat suggestion) executed by R. We should include this file & lines for installing stuff from the file in the minimal R template.

file to add:
```
install.R
```

lines for docker:

```
COPY install.R /tmp/install.R
RUN R -f /tmp/install.R
```

**Comment by rokroskar** [comment]
@emmjab I think this has been done and can be closed?

**Comment by emmjab** [comment]
Yes!
