### ISSUE TITLE
Folders `data` and `notebooks` are not created

### ISSUE THREAD

**Issue by leafty** [SwissDataScienceCenter/renku-project-template#6]
When creating a new project on the UI, `data` and `notebooks` are not created

**Comment by ableuler** [comment]
I think it is an issue of how the UI uses it and not of the project template itself: https://github.com/SwissDataScienceCenter/renku-ui/issues/296
Suggest to close this issue.

**Comment by leafty** [comment]
Let's just keep it open here while it's not solved, as the question might come back about differences between this repo and the contents of a new project.

**Comment by ableuler** [comment]
on hold for the moment: https://github.com/SwissDataScienceCenter/renku-python/issues/279
