### ISSUE TITLE
Could the prompt in the interactive session be a bit shorter

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku-project-template#62]
At the moment when I open a terminal window in an Interactive Env the prompt looks like this:

`jovyan@jupyter-jakub-2echrobasik1-kubas-2ddatascience-dbash-2d335595ca:/work/kubas-datascience-in-bash$ █`

Could we shorten/simplify that to smth as simple as
`renku%> █`
or 
`kubas-datascience-in-bash%> █` ?

**Comment by pameladelgado** [comment]
This has been changed already with powerline, see https://github.com/SwissDataScienceCenter/renku-jupyter/pull/75

**Comment by rokroskar** [comment]
done in https://github.com/SwissDataScienceCenter/renku-jupyter/pull/75
