### ISSUE TITLE
Suggestion: use pipenv by default in renku

### ISSUE THREAD

**Issue by nperraud** [SwissDataScienceCenter/renku-project-template#63]
According to me, Renku is suffering from the problem that it needs on one hand an exact `requirements.txt` file with pinned versions, but on the other hand user friendly `requirements.txt`/solution. 

This problem has been solved by pipenv. So I wonder if this should not become a default in renku. From an interface point of view, the user will not have to care about `requirements.txt` anymore which is a step toward a more friendly experience.

I understand, they might be other consideration at play here. I just wanted to share my opinion.

**Comment by emmjab** [comment]
I don't have a strong opinion about this, but one of the things we struggle with is user familiarity with the tools. `pipenv` might solve the problem of having to specify sw specifically in `requirements.txt` but now instead of a `requirements.txt` there's a `Pipfile` & `Pipfile.lock`.

Not sure what's better, thanks for sharing!

**Comment by rokroskar** [comment]
We've had some internal discussions about `pipenv` and its lack of support etc. It has lots of problems that will seemingly never get solved - it's not possible, for example, to update a single package and its dependencies, it always updates _all_ packages, which is far from desirable. 

But actually, @nperraud, I'm not sure what you mean by 

> Renku is suffering from the problem that it needs on one hand an exact requirements.txt file with pinned versions

it doesn't need an exact requirements file to function. But if you mean that for _reproducibility_ that is the best solution, then I agree. 

We've been looking at other tools like [poetry](https://python-poetry.org/) that might work better than `pipenv` for this purpose.

**Comment by rokroskar** [comment]
closing - pipenv is rife with problems, we are not likely to switch over to it any time soon. Thanks for the suggestion @nperraud !
