### ISSUE TITLE
make the renku-python version templateable

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-project-template#98]
Ideally, at the time of project creation, the version of renku-python installed in a project's docker image would be the same as the version of the client that was used to create the project. This is now easily done by overriding the renku-python version in the Dockerfile. We should make this version templateable so the client that is used to initialize the project can inject the version there. 

Use the default jinja filter to make sure that the template stays compatible with older versions of renku-python: https://jinja.palletsprojects.com/en/2.11.x/templates/#default

**Comment by ciyer** [comment]
> Ideally, the version of renku-python installed in a project's docker image would be the same as the version of the client that was used to create the project.

I do not see why this is ideal. I could have created a project a year ago, and now update to a current version of renku-python. That seems like a good thing.

**Comment by rokroskar** [comment]
This is just on project creation - this way we don't have to constantly change the templates to keep up with renku-python releases.

**Comment by rokroskar** [comment]
This has been implemented in #116
